name: CI

on:
    push:
        branches:
            - main
            - feature/*
        paths:
            - "gold_python/**"
            - "tests/**"
            - "requirements.txt"
    workflow_dispatch:

jobs:
    tests:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                # https://www.python.org/downloads/
                python-version: ["3.10", "3.11"]
        name: ${{ matrix.python-version }}
        steps:
            - uses: actions/checkout@v3

            - name: Setup python
              uses: actions/setup-python@v4
              with:
                  python-version: "${{ matrix.python-version }}"
                  architecture: "x64"

            - name: CI checks
              run: |
                  python3 -m pip install wheel
                  python3 -m pip install -r requirements.txt
            - name: Run tests
              run: |
                  pytest -v
